### ISSUE TITLE
Improve polynomical chaos expansion analysis element

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#101]
In the PCEAnalysis code we have a ToDo noting that we should

- [x] Implement calculation of multiple Sobol indices (Note: may require different orders for different qoi?)
- [ ] Add pd.read_hdf (https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#io-hdf5).
- [ ] ~~Test cp.fit_regression to approximate solver.~~

**Comment by jlakhlili** [comment]
1. Multiple Sobol indices: Done. 

2.  Read HDF5 file: create a proper issue for this enhancement.

3. Test `cp.fit_regression` should be moved in **new element**: Regression based Polynomial Chaos Expansion. The current PCE element is Pseudo-spectral projection (based in quadrature).

**Comment by dww100** [comment]
@jlakhlili Will you handle 2 & 3 - maybe make a feature branch for them if appropriate - possible a WIP pull request.

**Comment by jlakhlili** [comment]
@dww100 I will abandon the point 3 (at least if someone want to use it). I did some tests and I the method doesn't work well. In addition, I didn't  gain so much in term of computational time. So I think for the moment Pseudo-spectral projection method for the PCE element is enough for our applications.

**Comment by jlakhlili** [comment]
@dww100 for the point 2, yes I will create a a proper issue for it and a pull request... Is it ok for you?

**Comment by raar1** [comment]
I think this issue is now more or less addressed.
