### ISSUE TITLE
Add a test that checks restart works correctly

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#103]
Just put in a fix that ensured that reloaded `Campaign` picks up the active app from state file. This showed me the need for a good test of this. May need to implement `Campaign` comparison methods.

**Comment by orbitfold** [comment]
Can you put in a reference to the commit?

**Comment by raar1** [comment]
@orbitfold latest dev seems to have the changes (if you look in ```save_state()``` for example you'll see it now stores ```"active_app": self._active_app_name```)

@dww100 My issue with this (and the reason I was forcing the user to explicitly set the app themselves upon reload) is that the campaign doesn't store anything about the algorithm we're actually running. So it's not like you can just reload the campaign in a different script and then say "continue from where you were" kind of thing. I'm not totally against setting the last used app as a sensible default, but I worry it might give the wrong impression about what the tool does and doesn't handle. But I suppose that actually it probably always helps to know what the last app that was in use was (say, in the case of unexpected execution termination of the script)

**Comment by dww100** [comment]
@raar1 Maybe post M12, we should work with an 'alpha user' (as I call Robbie nowadays) to make a more intuitive system. I think your worry is reasonable but probably not than much of an issue at present as all workflows are probably going to use one app (issue is likely to end up related to how we handle #109 and other features for complex VVUQ algorithms).

**Comment by dww100** [comment]
@orbitfold Do you need any information? I'm not sure what you are looking for when you ask for a commit here. As @raar1 says the functionality is 'ready for release' in the `dev` branch.

**Comment by dww100** [comment]
The commit I was referring to was `872a477420d66c57062c1322bce7a4c209752c11`

**Comment by orbitfold** [comment]
I was looking for the changes that fix the issue you need testing for.

**Comment by dww100** [comment]
@orbitfold I'm not sure that is straight forward. Basically what we need a test for is that all of the variables in the Campaign are the same between a save and a restart from the saved state. Naturally all manner of things could happen in the database but that is beyond the scope of this.

**Comment by orbitfold** [comment]
> @orbitfold I'm not sure that is straight forward. Basically what we need a test for is that all of the variables in the Campaign are the same between a save and a restart from the saved state. Naturally all manner of things could happen in the database but that is beyond the scope of this.

I think it will be made a lot easier with the changes I'm making to the tests.

**Comment by dww100** [comment]
Cool

**Comment by raar1** [comment]
@orbitfold Would you say this test is more or less done now so I can close the issue (and include this in the v0.4 release today)?

**Comment by orbitfold** [comment]
I'd say more or less. The testing can always be more comprehensive.

**Comment by raar1** [comment]
Thanks. We can open a new, more specific issue when the time comes. For now I'm trying to clean up as many trailing issues as possible, so if this one is addressed for now I'll close it.
