### ISSUE TITLE
Choices/categorical variables

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#105]
We had a concept of choices or categorical variables where a set of discrete options for which a set of simulations were run. This is both useful for testing and potentially useful for VV applications.

**Comment by raar1** [comment]
With respect to the first paper, we need some way to add more replicas for a given category, even after the sampler (or however it is implemented) has finished. This is needed to increase sampling in regions which are found during analysis to have been very noisy.

This likely will involve #90.

**Comment by raar1** [comment]
As some way towards this, I've added a BasicSweep sampler, that will perform a parameter sweep through all variables for which a list of values is provided (using the product of all iterators).

**Comment by raar1** [comment]
After discussion with @dww100 , we will implement a "sampler of samplers" approach for this. Essentially, you can plug in one or more samplers to it, and it manages the product of the samplers.

**Comment by raar1** [comment]
I believe this is now addressed by PR #134 .

I wrote a sampler called ```Multisampler``` which you can construct as follows:

```
Multisampler(sampler1, sampler2, sampler3, ...)
```

to chain together as many samplers as you wish. This can be a sweep sampler with a random sampler, for example (thus handling the "category" variables case, but with more flexibility).

**Comment by raar1** [comment]
Issue is addressed by the SweepSampler and MultiSampler additions.
