### ISSUE TITLE
Implement comparison/validation element

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#108]
Currently we have a base comparison element defined, which requires the following method to be implemented:
```
    def compare(self, dataframe1, dataframe2): 
```
We currently have no implementations of any such comparison element. I think we should be thinking about adding one or two now, but I wonder if this prototype base class makes sense:

- Does this ```compare()``` method signature make sense?
- Should comparison elements be limited to only comparing dataframes?
- What about trying to compare, say, two columns from within the same dataframe?
- Perhaps only 'columns' should be passed to ```compare()```
- Should a comparison element have more standard methods than just ```compare()```?

We could of course just wait for the outcome of some of the discussions/theoretical work that should be happening for this, but I feel like some sort of simple "are these two data sets similar" validation should be possible to implement here to help us pick a reasonable design for the generic validation element.

**Comment by dww100** [comment]
Those seem sensible concerns.

I'm inclined to think we should have a blank or `*arg, **kwargs` and possibly have a `_valid_inputs` method skeleton which gets all arguments and checks if comparison can be made.

I tend to feel we should abstract from one or more actual use cases rather than try to guess. We might become more restrictive, or at least explicit over time.

**Comment by djgroen** [comment]
Hi both.

@wedeling and I have been working out a first VVP closely related to this, as part of the V&V dev team (Robin is in it too).

Have a look here for details and feel free to comment as you like:
https://github.com/djgroen/FabSim3/issues/141

Two last small points:
* The VVP is not FabSim3 code, but generic code with no major dependencies. It currently resides both in both the FabSim3 and the FabUQCampaign repository.
* We want to make a separate VVP repository as soon as we have two VVPs ready.

**Comment by orbitfold** [comment]
https://github.com/capitalone/datacompy

There is this thing out there

**Comment by raar1** [comment]
@orbitfold That looks promising, thanks.

**Comment by raar1** [comment]
I'm going to implement this using datacompy 0.6.0 now

**Comment by raar1** [comment]
This seems to be more than settled by e.g. [https://github.com/UCL-CCS/EasyVVUQ/blob/dev/easyvvuq/comparison/validate.py](https://github.com/UCL-CCS/EasyVVUQ/blob/dev/easyvvuq/comparison/validate.py)
