### ISSUE TITLE
Multi-campaign database is currently a bit of a mess

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#109]
At present the (sql) campaign database allows more than one campaign to be stored in it. There are a number of issues with this:
- As discussed in issue #67, having multiple campaigns from (even subtly) different easyvvuq versions is obviously problematic
- Currently we only have one RunTable. It feels messy, error-prone and (potentially) inefficient to be having multiple campaigns all dumping their runs into this one giant table, and then having to filter by campaign (on top of all the other filter criteria) to read/update the necessary runs.
- We have only one SamplerTable. This is similar to but less serious than the RunTable case, mainly because there are fewer samplers. However it's still a bit messy to have all the campaigns dump their samplers into the same table.
- Ditto for the AppTable.

The additional filtering and debugging needed to deal with the fact that more than one campaign could reside in the same database is making me wonder what the benefits are. Is it just to minimise how many database connections are made for a hypothetical application that uses loads of campaigns?

Instinctively I'd like to encapsulate the data in the sense of one database for one campaign, but I'm willing to be convinced otherwise. Any thoughts on this?

**Comment by dww100** [comment]
I don't think a single AppTable is an issue. Agree that the rest is a problem. I think we should wait until someone is proposing a use case before we make any changes though.

**Comment by orbitfold** [comment]
> * Currently we only have one RunTable. It feels messy, error-prone and (potentially) inefficient to be having multiple campaigns all dumping their runs into this one giant table, and then having to filter by campaign (on top of all the other filter criteria) to read/update the necessary runs.

That is kind of the SQL way of doing things though. In what way is it messy or error-prone?

> * We have only one SamplerTable. This is similar to but less serious than the RunTable case, mainly because there are fewer samplers. However it's still a bit messy to have all the campaigns dump their samplers into the same table.
> * Ditto for the AppTable.

Likewise.

**Comment by raar1** [comment]
I suppose my reasoning was it's messy because runs are very specific to a given campaign. so having to do additional filtering in all your queries makes the queries unnecessarily longer and more likely to need debugging. But I'm happy to continue as we are if you think this is normal. 

I tend to think of the database how I think about typical OO data encapsulation principles for e.g. classes, in which it would be obvious that each campaign should have its own runs table. But I understand that in the SQL approach maybe the sort of setup we have here is perfectly usual and safe enough?

**Comment by orbitfold** [comment]
It's probably the most common pattern in database design and databases are usually optimised quite well for it.

https://database.guide/the-3-types-of-relationships-in-database-design/

**Comment by raar1** [comment]
OK, thanks for that. In that case I'm happy to continue with the current design (apart from the collation, but I'm going to open a new issue for that one).
