### ISSUE TITLE
Make tutorials downloadable as Jupyter notebooks

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#113]
Feedback from alpha testers suggests this would be a much appreciated thing to provide. We can still lay it all out the same way it appears in the tutorial, but the users can play with it and try modifying things in a nicer environment.

**Comment by djgroen** [comment]
I just wanted to add that we've now established a very basic Python API for FabSim (see `lib/` subdirectory), which will allow it to be used from a Jupyter notebook if that is convenient. For Flee and the Ocean Model, I think this could be particularly useful.

But of course the Jupyter environment would break down if any tutorial contains console commands, so I suppose we really have to steer clear of that then.

**Comment by orbitfold** [comment]
https://pypi.org/project/rst2ipynb/
I'll try this.

**Comment by orbitfold** [comment]
But what does "downloadable" mean?

**Comment by orbitfold** [comment]
I'll close this.
