### ISSUE TITLE
Climate example

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#123]
Adaptive stochastic collocation would be nicest

**Comment by jlakhlili** [comment]
If we have an example of this application, we can use the 3 methods that we propose: SC, PCE, QMC and do a kind of UQ Benchmark.

**Comment by wedeling** [comment]
I'm back from vacation now, so I'll be working on this example. I could indeed try the different samplers

**Comment by wedeling** [comment]
Hi @raar1, I've started writing the climate example section in the paper. Most of my code is very similar to the coffee cup example which is already in the paper. The only real different is that I interface EasyVVUQ with FabSim3 to run the samples on Eagle in parallel. My thought was to only show the code pertaining to this, to avoid repetition, and provide a reference to the full code.

**Comment by wedeling** [comment]
@raar1 @jlakhlili  The 1st drafty version of the section of this example is more or less ready. Let me know what needs to be changed / added.

**Comment by raar1** [comment]
Nice, I think this is good now.
