### ISSUE TITLE
Establish flee example

### ISSUE THREAD

**Issue by djgroen** [UCL-CCS/EasyVVUQ#129]
We have an integration of Flee with EasyVVUQ, but we need to test it out with the latest codes, make sure the implementation captures a meaningful scenario, and clearly present it within the software paper.

**Comment by djgroen** [comment]
@cspgdds When you return, perhaps you can share what you have, and then we can work together to get this done fully?

**Comment by raar1** [comment]
@djgroen I'm going to close this now, as we have the example for the Applications Paper.
