### ISSUE TITLE
Chaospy collaboration

### ISSUE THREAD

**Issue by jonathf** [UCL-CCS/EasyVVUQ#131]
Hi, I am the maintainer of Chaospy. Thank you for using my code as part of your project. I am very humbled.

I was wondering, would you guys would be interested in some sort of collaboration?

For example to start, discrete distribution support discussed in #69. Would it make sense to move/copy the code over to the chaospy repository? This way the maintenance burden for that component get moved to Chaospy. I also imagine it is something of interest for more than just easyvvuq.

**Comment by raar1** [comment]
Hi @jonathf , thanks for getting in touch! Yes, we would be very happy to collaborate, and had been meaning to contact you as our tool becomes more mature.

Moving the discrete distribution to Chaospy would make sense for us, particularly as relates to maintenance as you say. If we can help with this let us know.

Thanks for making such a useful library!

**Comment by jonathf** [comment]
Glad to hear that. I'll make a pass at the task.

I have created a "Releated projects" section in the chaospy main README. Do you guys mind if I add your project there?

**Comment by raar1** [comment]
Not at all, please do.
