### ISSUE TITLE
Store Analysis results to database

### ISSUE THREAD

**Issue by jlakhlili** [UCL-CCS/EasyVVUQ#132]
Currently the analysis results are stored in a dictionary:
```python
results = {'statistical_moments': {},
           'percentiles': {},
           'sobols_first': {k: {} for k in qoi_cols},
           'sobols_total': {k: {} for k in qoi_cols},
           'correlation_matrices': {},
           'output_distributions': {},
           }
```
So, as discussed with Robin in the dev-team (FabSim/EasyVVUQ) meeting today, it will be better if we create new tables for results and store them in the data base after the analysis.  
It's what I did in the UQ tests for fusion application:

```python
# Get Descriptive Statistics for the pressure p
smp = results['statistical_moments']['p']
stp = results['sobols_total']['p']

# Store Stats and Sobols total indices in the database
engine = my_campaign.campaign_db.engine

smp_df = pd.DataFrame.from_dict(smp)
smp_df.to_sql('STATS_P', engine, if_exists='append')

stp_df = pd.DataFrame.from_dict(stp)
stp_df.to_sql('SOBOLS_TOT_P', engine, if_exists='append')
```
Finally, I have two additional tables `STATS_P` and `SOBOLS_TOT_P`.

**Comment by orbitfold** [comment]
I don't understand what needs to be done here.

**Comment by raar1** [comment]
I suppose we need to decide whether the correct place to store results is in the database. We could provide this functionality relatively easily, as Jalal shows. The question is how do we formalize this so it doesn't pollute the database with hundreds of tables filled with different versions of results. Surely we would rather have a "last result" type of thing? Or do we really want every single analysis result to be in there? Some outputs will be huge... I think we don't want this to be (necessarily) automatic.

I think a strong reason to allow something like what Jalal is asking for is if we are truly to have a restartable workflow, then the scale bridging between apps (which usually is built on some kind of "result") needs to know where to look for its input. However, it's clear that not every analysis element's "result" falls into that category.

**Comment by raar1** [comment]
@jlakhlili @orbitfold It's possible this would relate to how a scale bridging element would work (Issue #148). As in, what would it need as input.

**Comment by DavidPCoster** [comment]
@orbitfold -- do we want to create a new sql  table to store the results?  If so, which results?

**Comment by orbitfold** [comment]
> @orbitfold -- do we want to create a new sql table to store the results? If so, which results?

Post decoder results are already stored in the runs table as JSON. I think we can close this.

**Comment by raar1** [comment]
I think this was from a hackathon discussion 2 years ago and the design has changed greatly since then. Seems like it is satisfied in the current version, in any case, so I agree to close.
