### ISSUE TITLE
Add simple scale bridging element base class(es)

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#148]
To complete the multiscale (read, multiapp) framework for EasyVVUQ we would now need some sort of primitive scale bridging element. I'm thinking initially that one basic function of such an element could be e.g. outputting the distributions for variables in App-Y using the dataframe collated output of App-X.

How general is this? What other "scale bridging" operations do we expect?

Please discuss...

**Comment by raar1** [comment]
@orbitfold This is also some absolutely ancient issue from very early discussion on "multiscale" capabilities in easyvvuq. I suggest we close this, unless there is really some intention to add such a feature?

**Comment by orbitfold** [comment]
I'm all for it.
