### ISSUE TITLE
Check/Sanitize collation sql queries

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#149]
As @orbitfold noted in his review of PR #145:

> In easyvvuq/db/sql.py:
> 
> > @@ -839,6 +799,7 @@ def get_collation_dataframe(self):
>              The dataframe with all contents that were appended to this database
>          """
>  
> -        query = "select * from COLLATIONRESULT"
> +        tablename = 'COLLATION_APP' + str(app_id)
> 
> This seems quite error prone. Is there a reason to use sql queries directly?

**Comment by orbitfold** [comment]
This is no longer relevant with the new collation system.
