### ISSUE TITLE
File based encoder (should mostly replace fixtures)

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#154]
Now we have multi-encoders we should be able to create an Encoder which copies or links files based on parameters (possible with an optional lookup table). May need to think in terms of remote files (which @orbitfold has been looking in to) - for now I think this would be two separate encoders but we might end up with a local/remote flag and kwargs in a single generic interface.

**Comment by raar1** [comment]
This could be a good chance to remove the slightly messy fixtures code that sort of sits in any encoder, and have it all nicely contained in a single encoder. I think this is one of the few remaining issues about the core functionality/design that isn't quite right yet, but this should solve that.

**Comment by raar1** [comment]
There's a work-in-progress for this in PR #158

**Comment by raar1** [comment]
Merged
