### ISSUE TITLE
Campaign prefix 

### ISSUE THREAD

**Issue by jlakhlili** [UCL-CCS/EasyVVUQ#157]
It is better to have proper name of the campaign directory and database. For example,  instead of  EasyVVUQ_Campaign in  `EasyVVUQ_Campaign_uxaomko2/` and  `EasyVVUQ_Campaign_0zakp0gstest.db`, we can just use the campaign_name which can be given by the user.
I already did the correction, can I push it?

**Comment by raar1** [comment]
Hi Jalal - can you open a pull request for it?
