### ISSUE TITLE
Visualisation of results

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#16]
One of the major primitives currently completely absent from this prototype is any kind of visualisation of the results.

I've found this python library which is built on matplotlib:
https://seaborn.pydata.org/

Seems to do nice visualisations of data. Might be worth looking into.

**Comment by djgroen** [comment]
Hi guys. With the M9 release out, perhaps it's a good idea to start a separate activity around this in the next month or two? I still think it may make the most sense to do the viz in a separate tool, which could optionally rely on EasyVVUQ for decoding?

Any thoughts from your side?

**Comment by raar1** [comment]
I would agree with this @djgroen. I don't think we want EasyVVUQ to handle vis stuff at all.

**Comment by dww100** [comment]
I think the correct answer is that as part of M12 release we should have good documentation which shows how to create visually appealing and informative graphs from analyses.

**Comment by raar1** [comment]
We appear to have reached a consensus on this
