### ISSUE TITLE
uq.analysis.EnsembleBoot fails if replicas=1

### ISSUE THREAD

**Issue by fjansson** [UCL-CCS/EasyVVUQ#161]
In the gauss tutorial example, if replicas is set to 1, `uq.analysis.EnsembleBoot` fails with a backtrace. Apparently more than 1 replica is needed - a more descriptive error message would be helpful.

**Comment by orbitfold** [comment]
Hm, I can't replicate at least in the test_integration with replicas=1 it runs fine. Can you give me the complete set-up you used?

**Comment by fjansson** [comment]
I just tried again in the current dev branch "easyvvuq==0.3.1+180.gd60d425". 
`python3 easyvvuq_gauss_tutorial.py` runs fine as it is, but breaks if I change line 77 to `replicas=1`. 
```
# 5. Get run parameters
my_campaign.draw_samples(num_samples=3,
                         replicas=1)
```
[backtrace.txt](https://github.com/UCL-CCS/EasyVVUQ/files/3869873/backtrace.txt)

The tests pass for me as well. Side note, the README file could mention how to run the tests, now it just says that one has to compile cannonsim first. `py.test --pep8 easyvvuq/` seems to be what travis is using.

**Comment by orbitfold** [comment]
Ok, I can recreate it.

**Comment by orbitfold** [comment]
I think @velocirobbie commit fixed this? I think this can be closed.

**Comment by fjansson** [comment]
Yes, `easyvvuq_gauss_tutorial.py` now runs also with replicas=1 (current dev branch).
