### ISSUE TITLE
Ensemble bootstrap should give comprehensible error message if user gives wrong/non-existent qoi_cols

### ISSUE THREAD

**Issue by velocirobbie** [UCL-CCS/EasyVVUQ#164]

**Comment by orbitfold** [comment]
What is incomprehensible about the current one?

**Comment by raar1** [comment]
@velocirobbie Could you post a snippet of your script which was causing this problem? Then I'll write some sort of fix for it.

**Comment by velocirobbie** [comment]
if you add in test_worker.py line:167
```
    bootstrap = uq.analysis.EnsembleBoot(groupby=['Dist'],qoi_cols=["lastvx"])
    my_campaign.apply_analysis(bootstrap)
```
This does a bootstrap and works, if you change the qoi_col to something stupid it, you get an unhelpful KeyError:
```
    bootstrap = uq.analysis.EnsembleBoot(groupby=['Dist'],qoi_cols=["stupid"])
    my_campaign.apply_analysis(bootstrap)
```

**Comment by orbitfold** [comment]
I can do it instead I guess since @raar1 is busy.

**Comment by orbitfold** [comment]
See #179

**Comment by orbitfold** [comment]
Can we close this after I merge the PR?
