### ISSUE TITLE
white spaces in CSV column names cause pandas error

### ISSUE THREAD

**Issue by wedeling** [UCL-CCS/EasyVVUQ#168]
When I have spaces in the columns_names (the header) of an output CSV file:
```
qoi1, qoi2, qoi3, qoi4
```
Then collate() returns an error, related to
```        
            data = pd.read_csv(
            out_path,
            usecols=self.output_columns,
            header=self.header)
```
in `simple_csv.py` . This is because `self.output_columns` does not contain the spaces. I could just write column names with no spaces, or use
```
        data = pd.read_csv(
            out_path,
            usecols=self.output_columns,
            header=self.header,
            skipinitialspace=True)
```
The latter works, and I guess it should also work if there are no initial spaces in the column names, although I did not test this. Also,  I can imagine that a space at the end of a column name might still cause an error.

**Comment by orbitfold** [comment]
It's not an error, it's expected behaviour. CSV format does not allow for spaces. Well it does but they are considered part of the attribute name even if they follow or precede it. See: https://tools.ietf.org/html/rfc4180

**Comment by wedeling** [comment]
Thanks, did not know this. I suppose that in that case I just wrote a bad CSV file, and we don't really need to modify the toolkit. I'll just update the write subroutine of my solver.

Think we can close this?
