### ISSUE TITLE
Setup requirements

### ISSUE THREAD

**Issue by jlakhlili** [UCL-CCS/EasyVVUQ#177]
Update  `install_requires`  in **setup.py** (versions and  new external libraries): To be in step with **requirements.txt**.

**Comment by jlakhlili** [comment]
Yes, it's better to read requirements in setup.py from requirements.txt file.

**Comment by raar1** [comment]
Hi @jlakhlili I've fixed this in PR #178 , and it seems to be passing all tests.

Have a look and see if you're ok with it

**Comment by jlakhlili** [comment]
Thanks @raar1. It looks better now.
