### ISSUE TITLE
Use conda-pack to create a relocatable conda environment?

### ISSUE THREAD

**Issue by orbitfold** [UCL-CCS/EasyVVUQ#183]
https://conda.github.io/conda-pack/

**Comment by orbitfold** [comment]
I'm not 100% sure how much sense this make. One thing we definitely should do is explain the conda workflow in the documentation. Since not everyone is familiar with it.

**Comment by raar1** [comment]
I think @velocirobbie is our resident conda expert.

**Comment by velocirobbie** [comment]
Not sure why this is better than just having the requirements.txt? You have to have conda set up to use it so it doesn't make it much easier to set it up on a remote machine

**Comment by orbitfold** [comment]
Well I guess the idea is that you have a package you can download and install anywhere without bothering to instally python or conda first. I'm not sure if it's worth the effort either.

**Comment by orbitfold** [comment]
Are you referring to this: "While conda-pack requires an existing conda install, it can also be installed from PyPI:"? I think this is only true for the source machine, not for the target.
