### ISSUE TITLE
Create a google colaboratory for testing out EasyVVUQ?

### ISSUE THREAD

**Issue by orbitfold** [UCL-CCS/EasyVVUQ#187]
Could make a link to it first thing when people open this github page. Use the Jupyter notebooks we have generated from rst docs. I think it would make it seem more "real" and make a good first impression.

Might be of interest if we don't want to do this by hand:
https://stackoverflow.com/questions/50595831/google-colab-api

**Comment by raar1** [comment]
How mature is that API nowadays?

**Comment by orbitfold** [comment]
I've no idea. We don't have to use it. I doubt the basic tutorial will change very much and, while not ideal, uploading by hand takes only a couple of clicks.

**Comment by orbitfold** [comment]
So here is what we came up with. I think it's really cool:

https://colab.research.google.com/drive/1qD07_Ry2lOB9-Is6Z2mQG0vVWskNBHjr

**Comment by orbitfold** [comment]
I have added a link to it to our git hub "front page"

**Comment by raar1** [comment]
Wow, that's really nice. Is there a lot of manual effort to convert the notebooks to that, or can we just automate it?

**Comment by orbitfold** [comment]
It wasn't that hard. I think it's possible to automate it.
