### ISSUE TITLE
Better sales pitch?

### ISSUE THREAD

**Issue by orbitfold** [UCL-CCS/EasyVVUQ#188]
"The aim of this library is to facilitate verification, validation and uncertainty quantification (VVUQ) for a wide variety of simulations. This library is currently in an Alpha "friendly users" phase of development, with only a core number of UQ elements currently implemented."

I'm not sure how convincing it is or how well it explains the premise of EasyVVUQ. The opening statement should be stronger than that since this is what people will use to decide whether to stay or leave.

**Comment by raar1** [comment]
I think you're right. Perhaps we can also drop the "Alpha" statement now that it is (slightly) more mature?

**Comment by orbitfold** [comment]
Yeah, it does sound a bit uninviting.

**Comment by raar1** [comment]
We could always grab a bit of the intro from the Software release paper? I suppose that might sound better. Or would you rather keep it short and snappy?

**Comment by orbitfold** [comment]
I think it should address these three points - what it does and who is it for and how it stands out.
