### ISSUE TITLE
add input parameter for plot_grid()

### ISSUE THREAD

**Issue by arabnejad** [UCL-CCS/EasyVVUQ#189]
Hi EasyVVUQ dev team,
in the current implementation of `plot_grid` , there is not option to disable plot showing or save it as output file
I think that would be good if these option can be added as in the input parameters ?

**Comment by orbitfold** [comment]
Which file is this function in?

**Comment by arabnejad** [comment]
Hi Vytautas @orbitfold 
in this file `sc_analysis.py` 

```
    def plot_grid(self):
        """
        If N = 2 or N = 3 plot the (sparse) grid
        """
        import matplotlib.pyplot as plt

        if self.N == 2:
            fig = plt.figure()
            ax = fig.add_subplot(111, xlabel=r'$x_1$', ylabel=r'$x_2$')
            ax.plot(self.xi_d[:, 0], self.xi_d[:, 1], 'ro')
        elif self.N == 3:
            from mpl_toolkits.mplot3d import Axes3D
            fig = plt.figure()
            ax = fig.add_subplot(111, projection='3d', xlabel=r'$x_1$',
                                 ylabel=r'$x_2$', zlabel=r'$x_3$')
            ax.scatter(self.xi_d[:, 0], self.xi_d[:, 1], self.xi_d[:, 2])
        else:
            print('Will only plot for N = 2 or N = 3.')

        plt.tight_layout()
        plt.show()

```

**Comment by orbitfold** [comment]
Do you want to make a pull request or should I do it? I suppose an optional argument to specify the output file for the plot might be useful. @wedeling ?

**Comment by jlakhlili** [comment]
I think that the `plot` should be done in the application side. The user can save results in the Data base, output file and or plot them.

**Comment by wedeling** [comment]
Sorry for the slow reply, I'm on the road until the 22nd. I could add in an additional argument indeed to save the plot instead of showing it. On the other hand, there is something to be said to don't provide a plotting routine at all as @jlakhlili said. What do you think @arabnejad? Would you like to keep this routine?

**Comment by arabnejad** [comment]
Hi @wedeling 
My suggestion was based on the provided functionality and how to improve it for non GUI (because with the current version, user should close the plot window) 
also, as @jlakhlili  said , we can add it to examples and leave it to the user
however, having this functionality would be better option :)
I already fixed it, if you want I can make a pull request (currently I am in Italy, so I can do it by the end of this Thursday)
but it is up to you EasyVVUQ dev-teams ;) I am just suggesting :)
