### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#202]
Is it worth adding a badge that indicates the percentage of the code base that is currently covered by the tests? Maybe something like [https://coveralls.io/](https://coveralls.io/). That could help pinpoint areas which aren't being tested, or in any futute refactor of the tests etc.

What do you think, Testing Tsar @orbitfold ?

**Comment by orbitfold** [comment]
I approve.

**Comment by raar1** [comment]
OK I've set it up. You can see its output at e.g. [https://coveralls.io/github/UCL-CCS/EasyVVUQ?branch=dev](https://coveralls.io/github/UCL-CCS/EasyVVUQ?branch=dev).

Right now it's 25%, but tbh that's what I was expecting. I think it's useful that it shows you what lines in what source files aren't tested etc, so you can at least make sure critical stuff has tests first.
