### ISSUE TITLE
CII Best Practices

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#203]
This might be worth a try as well:
[https://bestpractices.coreinfrastructure.org/en](https://bestpractices.coreinfrastructure.org/en)

It's essentially self-assessed, but we already meet most of the basic requirements. It can also act as a good checklist to make sure the repo/code is accessible to outsiders.

**Comment by orbitfold** [comment]
can you make me repo owner pretty please ;)

**Comment by raar1** [comment]
I suppose this is the final stage in your ascent to Full Tsar?

**Comment by orbitfold** [comment]
Full Tsar is only the beginning.
