### ISSUE TITLE
Targets for v0.3

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#22]
* Allow extension of existing runs
* Versioning of outputs
* Combining of campaigns
* More complex/realistic encoders/decoders
  *  Ideally from outside collaborators
* Tools to pick up existing datasets

**Comment by dww100** [comment]
Created initial project: [https://github.com/UCL-CCS/EasyVVUQ/projects/3](https://github.com/UCL-CCS/EasyVVUQ/projects/3)

**Comment by raar1** [comment]
I've added a bunch of recent issues to the v0.3 Project section.

**Comment by raar1** [comment]
Closed as moving to M12 release planning at AHM.
