### ISSUE TITLE
Improve Analysis run time

### ISSUE THREAD

**Issue by jlakhlili** [UCL-CCS/EasyVVUQ#231]
The calculations in Analysis part can take quite a long time especially using a large number of parameters. This part is not optimized and it is still serial unlike the execution part witch can be parallelized using Dask or QCG-Pilot Job.  
Here is some ideas for improvements:
- Parallelization: use QCG-PJ like for the Encoding and the Execution @bartoszbosak.
- Is it still good to recall `cp.generate_quadrature` to get nodes, weights, or we can find a better way to use from Samplers (check memory)?
- Better usage of `chaospy fit_quadrature` and `cp.fit_regression` @jlakhlili @wedeling.
Other ideas are welcome.

Ps. Before, I will look for tools to do some profiling @orbitfold.

**Comment by wedeling** [comment]
How many parameters are you using? In the SC case the quadrature method becomes a bottleneck, but I think I can improve it, without parallelisation.

**Comment by jlakhlili** [comment]
I used 8 parameters, but I think that @DavidPCoster had bottleneck with 5 (3125 samples).

**Comment by DavidPCoster** [comment]
The reduced fusion model is quite fast:

98.7 ms += 11.8 ms per loop (mean +- std. dev. of 7 runs, 10 loops each)

and so now everything else is the bottleneck.  Using PCE with 5 varying parameters:

```
polynomial    samples   running  collation  analysis
  order       number     time     time       time
    2          1024       61.7      55.8       157.6
    3          3125      238.4     295.3       717.3
    3          3125      234.2     290.7       750.4
    4          7776      289.0    2757.5      4677.6
    4          7776      284.0    1583.6      5352.2
    5         16807      616.7    8567.1     14564.2
```
(there are some repeats to get a sense of the variability in timings).

**Comment by DavidPCoster** [comment]
Here is the output from doing

%prun old_campaign.apply_analysis(uq.analysis.PCEAnalysis(sampler=old_campaign.get_active_sampler(), qoi_cols=["te", "ne", "rho", "rho_norm"]))

[PCE.analysis.profile.txt](https://github.com/UCL-CCS/EasyVVUQ/files/4668601/PCE.analysis.profile.txt)

**Comment by orbitfold** [comment]
Analysis what? The issue should be edited to make it clearer which analysis classes you are talking about. I am assuming SC. That being said, yes, do profiling. Parallelising should be done as a last resort. I think the SC code can be still greatly improved in terms of a) efficiency b) clarity and c) testing and verification.

**Comment by jlakhlili** [comment]
I'm talking about PCEAnalysis, but SCAnalysis should have the same behaviour as far we are using chaospy with pandas dataframe...

**Comment by orbitfold** [comment]
https://jiffyclub.github.io/snakeviz/
This might help to better understand where most of the time is spent. You need to create a profiler output for it, for example like so:

python -m cProfile -o output_file.prof somescript.py

edit: also maybe you can try this https://github.com/jrfonseca/gprof2dot

**Comment by jlakhlili** [comment]
It seems the chaospy calls cost a lot:
![Screenshot from 2020-05-26 16-40-28](https://user-images.githubusercontent.com/16169832/82917110-3fe13280-9f73-11ea-9cba-69cba44e3425.png)

**Comment by wedeling** [comment]
I think I can improve the analysis quadrature in the SC method, but I'm now running into issues with a very long collation time. I think this is because we store the variables in the data frame as well, which is not required in the SC analysis. The problem is that I have a code now which has  many inputs (approx 900), but I only vary about 10 or 20. I also have a vector-valued QoI of 700 points, so the total data frame size is `N_samples* 700 x 900`. For 100 samples this already becomes very slow. In the SC analysis, I do not need the 900 parameter values, the only additional column I need is the unique `run_id` for each sample. So if I go to the collator (`aggregate_samples.py`) and I just comment out the input storage as:
```python
            # Use decoder to check if run has completed (in general application-specific)
            if decoder.sim_complete(run_info=run_info):

                run_data = decoder.parse_sim_output(run_info=run_info)

                if self.average:
                    run_data = pd.DataFrame(run_data.mean()).transpose()

                # mult = isinstance(run_data.columns, pd.MultiIndex)

                # params = run_info['params']
                # for param, value in params.items():
                #     if isinstance(value, list):
                #         # need to have multi-index dataframe
                #         if not mult:
                #             col, mult = multi_index_tuple_parser(run_data.columns.values)
                #             col = [(c, '') for c in col]
                #             run_data.columns = pd.MultiIndex.from_tuples(col)
                #         # add list values using columns tuple
                #         for i in range(len(value)):
                #             run_data[(param, i)] = value[i]
                #     else:
                #         run_data[param] = value
                # column_list = run_data.columns.tolist()

                # # we need to convert columns to tuples to account for multi-indexing
                # # should not influence non-multi-index frames, I hope. hacky?
                # # TODO from Jalal: I think we don't need it, must be handled in the decoder
                # if any([isinstance(x, tuple) for x in column_list]):
                #     column_list_ = []
                #     for column in column_list:
                #         if not isinstance(column, tuple):
                #             column_list_.append((column, ''))
                #         else:
                #             column_list_.append(column)
                #     column_list = column_list_

                # # Reorder columns
                # run_data = run_data[column_list]
                run_data['run_id'] = run_id
                run_data['ensemble_id'] = run_info['ensemble_name']
                new_data = new_data.append(run_data, ignore_index=True)
                processed_run_IDs.append(run_id)
```

Now the runtime is much better, and I did not have to modify the SC analysis at all. @jlakhlili : in the PCE analysis, do you need the parameter values? Do we need them anywhere at all for that matter? If not it seems like a waste of memory, if the vector-valued QoI are stored one entry per row, but this is another issue (#209).

**Comment by jlakhlili** [comment]
@wedeling In PCE, we don't use parameter values for the analysis, 
But in PCE the greedy part is the Sobol calculations. We use chaospy in this case.
Maybe we can use your routines, in this case we have to externalise them from SCAnalysis etc..
