### ISSUE TITLE
Making EasyVVUQ available via anaconda?

### ISSUE THREAD

**Issue by DavidPCoster** [UCL-CCS/EasyVVUQ#233]
Is there interest in making EasyVVUQ available via anaconda?

The procedure described at

https://docs.anaconda.com/anaconda-cloud/user-guide/getting-started/

doesn't seem to be too complicated ...

**Comment by orbitfold** [comment]
Ok, I will look to see if this can be done easily enough. Also would be nice if it is possible to write a github workflow that would do this automatically for each release. Like we have now for pypi.

**Comment by DavidPCoster** [comment]
"How to Setup Automatic Uploads to Anaconda from Travis CI in 15 minutes"
https://gist.github.com/zshaheen/fe76d1507839ed6fbfbccef6b9c13ed9

**Comment by orbitfold** [comment]
so doing that merely results in this: https://anaconda.org/orbitfold/easyvvuq

Which I'm not sure accomplishes what. If you want to do `conda install something` you need to add to a channel which I think you need to do via conda-forge  https://conda-forge.org/#add_recipe

**Comment by orbitfold** [comment]
I'll try to ask around for advice from people who have done this.

**Comment by orbitfold** [comment]
Ok, apparently it should be possible to install it with `conda -c orbitfold easyvvuq` but I need to add a meta.yaml file and somehow automate the build procedure, probably similar to what @DavidPCoster posted. We don't do this from Travis though, we use github actions: https://github.com/features/actions

**Comment by orbitfold** [comment]
I managed to make it at least find it via `conda -c orbitfold easyvvuq` but there is an issue with some packages that are only available via pip and not on anaconda.

**Comment by orbitfold** [comment]
https://stackoverflow.com/questions/37541084/cant-specify-pip-dependency-in-conda-meta-yaml-file

It's starting to look like it's more trouble than it's worth.

**Comment by orbitfold** [comment]
And of course you have to manually add all the dependencies:

"RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/scikit-learn/"

Although I think it should be possible to write a script that takes requirements.txt or something

**Comment by orbitfold** [comment]
I have found an easier way which is to do:

`conda skeleton pypi easyvvuq`
`conda build easyvvuq`

The first line creates a meta.yaml file by fetching info from pypi and the second attempts to build it. However it does not work because conda only contains outdated versions of, for example, salib and does not contain some packages at all. So we would have to build and probably maintain those packages ourselves.

**Comment by orbitfold** [comment]
So, thoughts?

**Comment by LourensVeen** [comment]
I think you can install using pip in a Conda environment, right? If EasyVVUQ is all Python, what would a Conda build add?

**Comment by DavidPCoster** [comment]
conda keeps a list of items that it installed, as does pip --- the system seems to get a bit confused  if you mix the two with sometimes conflicting requirements ...

See https://www.anaconda.com/blog/using-pip-in-a-conda-environment

But, yes, it is possible to pip install in an anaconda environment...

**Comment by LourensVeen** [comment]
Ah, fair enough. And pip doesn't need any help to get confused anyway...

I don't use Conda much, but I am planning on getting MUSCLE 3 into Conda Forge, and if I have to add and maintain the dependencies as well then so be it. But MUSCLE 3 is a native library, and the alternative for C++ and Fortran is to compile from scratch. Conda really adds something there. For EasyVVUQ, there's pip as an alternative.

I guess it depends on how many users you have that want to use Conda, and how willing you are to make an effort to support them then...

**Comment by orbitfold** [comment]
So hopefully it wont take any effort. If I can get that github action to work.

**Comment by orbitfold** [comment]
I guess I can close this now?

**Comment by DavidPCoster** [comment]
Thanks again!  Great job ...
