### ISSUE TITLE
Get rid of the master branch?

### ISSUE THREAD

**Issue by orbitfold** [UCL-CCS/EasyVVUQ#236]
I can delete it and rename dev to master. It does not seem to provide any benefits and it can and did cause confusion.

**Comment by raar1** [comment]
Not opposed, but in such a case I would strongly suggest you add a rule preventing anything being merged which is breaking the tests (as a bare minimum). Contributions should be sitting as PRs until the changes have been reviewed and all tests are passing, otherwise things will get messy.

**Comment by orbitfold** [comment]
Yeah, they should shouldn't they. It's a bit hard to convince people to work that way. One option would be to remove everyone's write access. Not sure how well that would go down.

**Comment by raar1** [comment]
I think adding a rule here might be enough to enforce it: https://github.com/UCL-CCS/EasyVVUQ/settings/branches
We already have one protecting the master branch (although only for PR reviews). I think it's possible to tie it to the test results too.

**Comment by orbitfold** [comment]
Ah brilliant. I can then begin slowly tightening the noose.
