### ISSUE TITLE
Chaospy 3.2.10 breaks the dimension adaptive sampler

### ISSUE THREAD

**Issue by wedeling** [UCL-CCS/EasyVVUQ#243]
The new version of chaospy  changes the quadrature weights, at least for the uniform distribution:

New chaospy 3.2.10, quad weight for uniform dist, order 0 and 1
```
In [6]: cp.generate_quadrature(0, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[6]: (array([[1.]]), array([1.]))

cp.generate_quadrature(1, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[7]: (array([[0.9, 1. , 1.1]]), array([0., 1., 0.]))
```
Old chaospy (3.0.17), quad weight for uniform dist, order 0 and 1

```
cp.generate_quadrature(0, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[2]: (array([[1.]]), array([1.]))

cp.generate_quadrature(1, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[3]: (array([[0.9, 1. , 1.1]]), array([0.16666667, 0.66666667, 0.16666667]))
```
Note that in the new version the weights are zero at the edges for order 1. Similar behavior occurs at higher order. With these new weights the dimension adaptive sampler does not work properly.

Another thing I noticed is this:

```
cp.generate_quadrature(1, cp.Uniform(0.9, 1.1))
/home/wouter/.local/lib/python3.7/site-packages/chaospy-3.2.10-py3.7.egg/chaospy/quadrature/clenshaw_curtis.py:107: RuntimeWarning: invalid value encountered in true_divide
  weights /= numpy.sum(weights)
Out[20]: (array([[0.9, 1.1]]), array([nan, nan]))
```
This used to work in 3.0.17, now it gives nan as weights. @jlakhlili if you do `cp.generate_quadrature(1, cp.Uniform(0.9, 1.1))`, do you get same same result?

**Comment by jlakhlili** [comment]
@wedeling Yes, I have the same error. But, it's fine when I do:

```
In [14]: cp.generate_quadrature(1, cp.Uniform(0.900000001, 1.1))                                                                                                       
Out[14]: (array([[0.9, 1.1]]), array([0.5, 0.5]))

In [15]: cp.generate_quadrature(1, cp.Uniform(0.899999999, 1.1))                                                                                                       
Out[15]: (array([[0.9, 1.1]]), array([0.5, 0.5]))
```
We have to report this to @jonathf and create an issue in chaospy repo.

**Comment by jlakhlili** [comment]
Beside this issue, when we want to use `fit_quadrature`, it's important to know the polynomial order that we have to use regarding the quadrature order. But, the argument **order** in `cp.generate_quadrature` is a bit confusing. I don't know if it correspond to "polynomial_order" or "polynomial_order+1", etc... For example, in uncertainpy, they use "polynomial_order+2"!

**Comment by wedeling** [comment]
@jlakhlili OK thanks. We can report this. In the mean time I'll revert to using 3.0.17.

If you want a surrogate of poly order p, you need p+1 points, so that's why they use polynomial_order p+1 I think. As we discussed before, perhaps its better to just rename
polynomial order to quadrature_order, which is more consistent.

**Comment by jonathf** [comment]
A fix should now be in place solving both of the quadrature problems in Chaospy version 3.2.12.

**Comment by wedeling** [comment]
@jonathf Thanks! I'll test it

**Comment by wedeling** [comment]
It worked, thanks again
