### ISSUE TITLE
`sampler` vs. `sample` - inconsistency

### ISSUE THREAD

**Issue by bartoszbosak** [UCL-CCS/EasyVVUQ#255]
Once I tried to employ the filtering over sampler type in the `list_runs()` I've got the following error:
`sqlalchemy.exc.InvalidRequestError: Entity '<class 'easyvvuq.db.sql.RunTable'>' has no property 'sampler'`

After short investigation, I've realised that there is some inconsistency: It looks like everywhere in the core code of the easyvvuq the name `sampler` is used, but inside the `RunTable` definition, we have a name `sample` instead. 

For now, I've applied a small fix that seems to resolve my issue, namely I've changed the following code in `sql.py`:
```
if sampler:
      filter_options['sampler'] = sampler
```
to 
```
if sampler:
      filter_options['sample'] = sampler
```

The first question is if this fix doesn't generate hidden side-effects and the second if we shouldn't make naming uniform across the whole code (e.g. use `sampler` everywhere or use `sample` everywhere).

**Comment by jlakhlili** [comment]
@orbitfold  do you had a special reason for the difference between `RunTable` and the core code concerning `sample/sampler` entry or is it just a naming mistake?
I think, @bartoszbosak needs to have `sample` as filter, with consistency, to manage `multi_campaign` interface in [EasyVVUQ-QCGPJ](https://github.com/vecma-project/EasyVVUQ-QCGPJ/tree/dev-multi-app).
He already did a correction there: https://github.com/UCL-CCS/EasyVVUQ/tree/hotfix_sampler

**Comment by orbitfold** [comment]
Please change it to sampler. There seems to be a typo in the SamplerTable class where the `__tablename__` attribute seems to be set to sample. I think it should be sampler. So please change it accordingly making sure it is consistent with the rest of the code base. Or if you want me to do it I would like to do it after the Kubernetes PR since it is very big.
