### ISSUE TITLE
Generic CSV parsing issues (decoder)

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#26]
Want to allow user to pass args to pandas reader - original idea of kwargs failed.

**Comment by raar1** [comment]
I've made sure simple_csv decoder purges all non-pandas keywords from its kwargs before feeding them to pandas.read_csv(). This means you can now pass arbitrary pandas arguments (all those not recognized by simple_csv will be automatically passed on to read_csv. It's now on the dev branch.

I think this fixes the problem - go ahead and reopen if you disagree ;)

**Comment by raar1** [comment]
test_cannonsim.py is currently testing this functionality by passing "header=0" in uq.collate.aggregate_samples(), which is then fed through to the decoder (and eventually read_csv())
