### ISSUE TITLE
Uniformity in support for multivariate distributions among Samplers

### ISSUE THREAD

**Issue by YehorYudinIPP** [UCL-CCS/EasyVVUQ#262]
I would be nice to have the ability to pass a 'vary' parameter for every sampler with keys describing a joint distribution.

For some time I was using the` PCESampler` with parameters with a multivariate distribution.  For instance, I could pass the `vary` for 3 parameters with 2-dimensional multivariate distributions in the following form:

`
{'te.value': J(Normal(mu=2875.60131987301, sigma=575.120263974602), Normal(mu=2395.68589115807, sigma=479.137178231614)),
 'te.ddrho': J(Normal(mu=-2654.58327935538, sigma=-530.916655871076), Normal(mu=-5539.09665125111, sigma=-1107.819330250222)),
 'ti.value': J(Normal(mu=1781.15627304028, sigma=1781.15627304028), Normal(mu=1302.31441865118, sigma=1302.31441865118))}
`

And in this way, the `PCESampler` treats it as 6 parameters, which is what I want in this case.

However, if I use it with `QMCSampler` or `SCSampler`, it would treat it as 3 parameters.
And if I use a 'QMCSamler' with such a vary to draw samples from a campaign it would give me the following error: 

```
~/.local/lib/python3.6/site-packages/easyvvuq/campaign.py in draw_samples(self, num_samples, replicas)
    515
    516             list_of_runs = [new_run for i in range(replicas)]
--> 517             self.add_runs(list_of_runs)
    518
    519             num_added += 1

~/.local/lib/python3.6/site-packages/easyvvuq/campaign.py in add_runs(self, runs)
    450
    451             # Verify and complete run with missing/default param values
--> 452             new_run = app_default_params.process_run(new_run, verify=self.verify_all_runs)
    453
    454             # Add to run queue

~/.local/lib/python3.6/site-packages/easyvvuq/params_specification.py in process_run(self, new_run, verify)
    107
    108                 logger.error(msg)
--> 109                 raise RuntimeError(msg)
    110
    111         return new_run

RuntimeError: Error when verifying the following new run:
{'te.value': 1232.4999713269597, 'te.ddrho': -4171.396245044672, 'ti.value': -3307.5537890572436}
Identified errors were:
{'te.ddrho': ['must be of list type'], 'te.value': ['must be of list type'], 'ti.value': ['must be of list type']}

```

I think it would be good to have a support for multivariate distributions for all the sampler classes.
Also, it would be great to give a description to which kind of `vary` dictionaries are supported in sampler class description.

**Comment by jlakhlili** [comment]
The issue here is more about the type of parameters.
Only PCE support `lists`.  We have to generate it.
For the moment you can split your list on scalars. The multivariate distribution will be build by the sampler.

**Comment by jlakhlili** [comment]
As discussed with @orbitfold and @wedeling in #easyvvuq Slack channel, vector inputs do not make sense.
So, PCE sampler will not support anymore list.
