### ISSUE TITLE
Error in example Colab

### ISSUE THREAD

**Issue by guy1ziv2** [UCL-CCS/EasyVVUQ#263]
The Colab example https://colab.research.google.com/drive/1qD07_Ry2lOB9-Is6Z2mQG0vVWskNBHjr gives an error during execution:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-b7702a541f31> in <module>()
----> 1 my_campaign.collate()

8 frames
/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py in _validate_usecols_names(usecols, names)
   1231     if len(missing) > 0:
   1232         raise ValueError(
-> 1233             "Usecols do not match columns, "
   1234             f"columns expected but not found: {missing}"
   1235         )

ValueError: Usecols do not match columns, columns expected but not found: ['ti']`

**Comment by guy1ziv2** [comment]
Seems like in several places the code assumes two columns in output.csv ["te", "ti"] whereas the cooling model only produces "te" column...

**Comment by orbitfold** [comment]
The tutorial is outdated. I have been working hard on a new one and I will put it up soon enough I hope. But thank you very much for your interest! Can I ask what you want to use EasyVVUQ for? The project is in early stages still and we are looking for use cases to accommodate... So if I can understand yours I can make sure you get the most use out of EasyVVUQ.

**Comment by guy1ziv2** [comment]
We are using simple ecosystem models (https://github.com/natcap/invest , developed by Natural Capital Project where I was Lead Scientist before moving to UK in 2003) and want to explore their global sensitivity to parameters representing specific biophysical characteristics of different land covers (e.g. depth of roots for wheat). These are stored in a CSV file, and the model which is determinstic is in Python.

**Comment by guy1ziv2** [comment]
What I am missing in EqayVVUQ is anything like History Matching or ABC to allow narrowing support of parameters or get a posterior parameters estimation based on observations. Is that planned for EasyVVUQ?

**Comment by orbitfold** [comment]
If you have the patience to work with us on this then yes. I would need to know what kind of workflow you would expect from this. It would be of tremendous help if you could just write down some Python pseudocode detailing how you would run this. Preferably in a new issue. I am not overly familiar with history matching but from a cursory read I think it would definitely worthwhile to at least see how this scenario fits in to the framework. 

Another thing, what are the execution requirements for your model? E.g. resources, how long it is expected to take to complete a single run, etc.
