### ISSUE TITLE
Should we rename quasi montecarlo to variance-based sensitivity analysis?

### ISSUE THREAD

**Issue by orbitfold** [UCL-CCS/EasyVVUQ#269]
I mean it is not some general quasi Monte Carlo method or framework. So it might be confusing to people.

**Comment by orbitfold** [comment]
Or maybe the Sobol method or something like that.

**Comment by wedeling** [comment]
Yes the way it is implemented it always runs N = n_mc*(n_params + 2) samples, instead of the n_mc specified by the user. Same for the MCSampler. So we could rename, or introduce a flag that switches between n_mc and N samples.

**Comment by wedeling** [comment]
Also the QMC sampler always uses Sobol sequences for the sampling plan. Other quasi-random sampling plans are not implemented in the current version.

**Comment by DavidPCoster** [comment]
Do we want to generalise it too offer other possibilities?  Or to rename it so that it doesn't seem to offer more than it actually delivers?
