### ISSUE TITLE
Read initial runs from file

### ISSUE THREAD

**Issue by tjdodwell** [UCL-CCS/EasyVVUQ#318]
Hi All,

Working with EasyVVUQ for the first time - https://github.com/tjdodwell/VECMA-hackathon

Sorry for the basic questions, but I can't see in an example how parameters for set of runs can be read in from a file / dataframe. Examples seem to define distributions for parameters.

Thanks in advance.

Tim

**Comment by orbitfold** [comment]
Hello Tim, can you describe your use case a bit? If you want we can have a call about it.

**Comment by tjdodwell** [comment]
We are using easyvvuq to manage the runs of computer simulation (in this case 1D heat equation for testing).

Here is a bit of the simple example.

```
campaign = uq.Campaign(name="Conduction.")
encoder = boutvecma.BOUTEncoder(template_input="models/conduction/data/BOUT.inp")
decoder = boutvecma.SimpleBOUTDecoder(variables=["T"])
params = {
    "conduction:chi": {"type": "float", "min": 0.0, "max": 1e3, "default": 1.0},
    "T:scale": {"type": "float", "min": 0.0, "max": 1e3, "default": 1.0},
    "T:gauss_width": {"type": "float", "min": 0.0, "max": 1e3, "default": 0.2},
    "T:gauss_centre": {"type": "float", "min": 0.0, "max": 2 * np.pi, "default": np.pi},
}

campaign.add_app("1D_conduction", params=params, encoder=encoder, decoder=decoder)

vary = {
    "conduction:chi": chaospy.LogUniform(np.log(1e-2), np.log(1e2)),
    "T:scale": chaospy.Uniform(0.5, 1.5),
}

sampler = uq.sampling.PCESampler(vary=vary, polynomial_order=3)
campaign.set_sampler(sampler)

campaign.draw_samples()

run_dirs = campaign.populate_runs_dir()

print(f"Created run directories: {run_dirs}")

time_start = time.time()
campaign.apply_for_each_run_dir(
    uq.actions.ExecuteLocal(os.path.abspath("build/models/conduction/conduction -d ."))
)
time_end = time.time()

print(f"Finished, took {time_end - time_start}")

campaign.collate()
```

Instead of using PCESampler - we would like to define the samples manually define in what ever is the most convenient way (csv file, numpy array, data frame - what ever). This is because all the code we have for the statistical analysis for sequential design of experiments is currently written in R. So we will be doing batches of runs to build emulators.

Does this make sense?

Thanks for your help.

**Comment by orbitfold** [comment]
I could write some kind of a "CSVSampler" that takes values from a CSV file I suppose. It's a matter of a couple of hours if you really need it. I am a bit confused though. Do you want to use EasyVVUQ simply for execution? What will you do with the results? Do you want them in a CSV file as well?

**Comment by tjdodwell** [comment]
@orbitfold thanks for your quick reply!

Yes we are using it to handle execution of an ensemble of run - for now for test problems - but later for large scale simulation. We will then use the runs to build an emulator of the computer model using another package "mogp" (developed at Turing in another of our projects). We will then have a number of cycles of experimental design (i.e solving new parameter values) to sequentially improve the emulator.

We are using easyVVUQ in this way, since it gives a common data structure for others to use the runs - many of these will use more of the functionality in easyvvuq as supervised by Peter Coveney.

**Comment by orbitfold** [comment]
Ok, the CSVSampler I will prepare. However, for mogp, why not create an EasyVVUQ analysis class? I can do that as well. Since we already have some initial work with regards to Gaussian Processes I can look at wrapping mogp as well. We currently use scikit learn for this, where GP support seems quite basic.

**Comment by tjdodwell** [comment]
That is super helpful - thank you!

linking mogp would be great (for me!) - others at Exeter use the R version of mogp and or other packages. So both would be useful, so help all possible uses!

**Comment by orbitfold** [comment]
@tjdodwell There is now a easyvvuq.sampling.CSVSampler, see if it suits your needs, let me know if you need any changes. I just did very basic tests.

**Comment by tjdodwell** [comment]
Thank you so much. I will have a go this afternoon, and get back to you!

**Comment by orbitfold** [comment]
@tjdodwell any updates on this?

**Comment by orbitfold** [comment]
I'm closing this.
