### ISSUE TITLE
How to log UQPs/VVPs - inherit from common base classes

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#32]
Recent changes to *coders used metaclasses to log their existence. The current logging via a campaign is adhoc and probably problematic if you call the UQP from outside EasyVVUQ.

**Comment by djgroen** [comment]
IMHO The UQPs and VVPs should ideally be portable pieces of implementation. So, I would not normally expect them to  be called from outside EasyVVUQ: rather, I'd expect other developers to involve them directly in their own tools...

**Comment by dww100** [comment]
I think it depends on what you mean (I may have articulated this badly in the opening post). Really what I mean is if the UQP is called with a pandas dataframe or a file as opposed to with a Campaign object as input.

**Comment by dww100** [comment]
With the new refactoring we discussed tracking:
primitive name/id, version, success, result directory, info

**Comment by raar1** [comment]
Addressed by merge #50
