### ISSUE TITLE
is "encoder_decoder_tutorial.ipynb" supposed to be runnable?

### ISSUE THREAD

**Issue by DavidPCoster** [UCL-CCS/EasyVVUQ#348]
If I try to run this notebook, I get

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-f0faa4b81c8e> in <module>
----> 1 copy_encoder = uq.encoders.CopyEncoder("source.txt", "root/folder1/target.txt")

/Volumes/Samsung8TB/dpc/GIT/EasyVVUQ/env/lib/python3.9/site-packages/easyvvuq-0.9.3+137.gc654d49e.dirty-py3.9.egg/easyvvuq/encoders/copy_encoder.py in __init__(self, source_filename, target_filename)
     35         self.target_filename = target_filename
     36         if not os.path.isfile(self.source_filename):
---> 37             raise RuntimeError("Specified source file does not exist:", source_filename)
     38 
     39     def encode(self, params={}, target_dir=''):

RuntimeError: ('Specified source file does not exist:', 'source.txt')

**Comment by orbitfold** [comment]
It's not supposed to be runnable. I will see if I can make those cell un-evaluatable

**Comment by orbitfold** [comment]
that seems to be easier said than done

**Comment by DavidPCoster** [comment]
I found and implemented a solution in the changes that were just merged with dev.

(Basically a try/except)

**Comment by orbitfold** [comment]
There is the option of adding
%%script false --no-raise-error
to the start of each cell, but looks ugly. Better than having to add explicit try excepts everywhere though I guess.

**Comment by DavidPCoster** [comment]
It was only one cell that needed this ...

**Comment by orbitfold** [comment]
Ok I compromised and added it only to the cells that fail.
