### ISSUE TITLE
Incorrect dependency versions?

### ISSUE THREAD

**Issue by JonMcCullough** [UCL-CCS/EasyVVUQ#357]
Running 'pip3 install easyvvuq' failed for Python 3.6 with the following error message:

Collecting chaospy==4.3.2 (from easyvvuq)
  Could not find a version that satisfies the requirement chaospy==4.3.2 (from easyvvuq) (from versions: 2.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 3.0.0, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.0.16, 3.0.17, 3.0.18, 3.1.0b0, 3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.3, 3.2.4, 3.2.5, 3.2.6, 3.2.7, 3.2.8, 3.2.9, 3.2.10, 3.2.11, 3.2.12, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.3.8, 3.3.9, 4.0b1, 4.0b2, 4.0b3, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.2.5, 4.2.6, 4.2.7)
No matching distribution found for chaospy==4.3.2 (from easyvvuq)

The chaospy documentation suggests at least Python3.7 is needed for version 4.3.2. The EasyVVUQ README file suggest Python3.6 should suffice.

Is the suggested solution to update to Python3.7 or manually installing EasyVVUQ?

**Comment by orbitfold** [comment]
Hi, only Python 3.7 onwards is supported... I will update the README.

**Comment by JonMcCullough** [comment]
Thanks for the clarification. I'll update to 3.7 on my machine.
