### ISSUE TITLE
Analysis of Multiple QOIs with Dimension-Adaptive Sparse Grids

### ISSUE THREAD

**Issue by joconnor22** [UCL-CCS/EasyVVUQ#375]
Hi

Thanks everyone for your work in maintaining this package.

I'm doing some work with the dimension-adaptive sparse grid sampling for a turbulent channel-flow problem. Everything seems to be working fine up until I get to the analysis part. A brief description of the problem is given below.

The quantities that I'm interested in are the friction Reynolds number, which is a scalar value, and some cross-channel statistics (e.g. streamwise velocity, Reynolds stress etc.) which are vectors. So I have `qoi_cols = ['Re', 'umean', 'uu', 'vv', 'ww', 'uv']`. To guide the dimension adaptive sampling I use the (scalar) Reynolds number, so I have `analysis.adapt_dimension('Re', data_frame, store_stats_history=True, method='surplus')`.

This all seems to work and I have some initial results which are all decoded fine. However, in addition to performing the analysis on the Reynolds number, I would also like to examine the resulting statistical moments of the cross-channel (vector) QOIs. However, when I try to get the cross-channel mean and variance of one of the other QOIs, via `mean = results.describe('uv', 'mean')`, it returns the (scalar) mean of **Re** (not a vector of means for **uv**). After playing around with it a bit on a different test problem, I've noticed that when I swap the order in **qoi_cols** it always return the mean and var of the first element in the list (e.g. `qoi_cols[0]`).

I had a quick look in the _sc_analysis.py_ module and it looks like the _SC2PCE_ function copies the **pce_coefs** for the first QOI into all of the others. I'm not really familiar enough with what is happening though to properly understand what is going on or if I'm doing something wrong. I've had a brief chat with Wouter and he suspects it may be a bug and has asked me to open an issue for it.

Thanks in advance for your help.

Kind Regards
Joe

**Comment by wedeling** [comment]
Hi @joconnor22 I am late with this, but will pick this up soon.

**Comment by joconnor22** [comment]
Hi Wouter, great thanks very much. It is much appreciated.

**Comment by wedeling** [comment]
Hi @joconnor22, see https://github.com/UCL-CCS/EasyVVUQ/pull/383. You should have received an invite to be a collaborator as well.

**Comment by wedeling** [comment]
This issue is closed, and merged into dev branch via https://github.com/UCL-CCS/EasyVVUQ/pull/383
