### ISSUE TITLE
Older version for basic_tutorial

### ISSUE THREAD

**Issue by mbergmann1324** [UCL-CCS/EasyVVUQ#380]
Could it be that the version for the basic_tutorial is outdated. 
When running "campaign = uq.Campaign(name='beam', params=params, encoder=encoder, decoder=decoder)" I get an error when running on my cluster. I needed to use Actions provided to me by Wouter. Also using the Triangle function leads to an error.

The code that works for me/us:
```from easyvvuq.actions import CreateRunDirectory, Encode, Decode, ExecuteLocal, Actions
execute = ExecuteLocal("{}/beam input.json".format(os.getcwd()))
 actions = Actions(CreateRunDirectory(root="/toks/work/mberg/astra7_IDA/python_scripts/", flatten=True), Encode(encoder), execute, Decode(decoder))
campaign = uq.Campaign(name="beam", params=params, actions=actions)
vary = {"F": cp.Normal(1, 0.1), "L": cp.Normal(1.5, 0.01), "a": cp.Uniform(0.7, 1.2)}  # , "D": cp.Triangle(0.75, 0.8, 0.85)}
campaign.set_sampler(uq.sampling.SCSampler(vary=vary, polynomial_order=3))
campaign.execute().collate(progress_bar=True)```

**Comment by djgroen** [comment]
Edited original comment to show code in fixed font format.

**Comment by djgroen** [comment]
I just ran the basic tutorial on my local machine after updating EasyVVUQ to the latest version, and it seems to work properly for me. @wedeling could you perhaps see if you can reproduce this error?

If not, should we still update the tutorial to use this action coe?

**Comment by wedeling** [comment]
The tutorial works.

**Comment by wedeling** [comment]
The tutorial work for me too. Closing
