### ISSUE TITLE
Failures when running the non-regression tests manually (2)

### ISSUE THREAD

**Issue by DavidPCoster** [UCL-CCS/EasyVVUQ#388]
When running the non-regression tests manually, I get the following:

>       assert(os.path.isfile(os.path.join(tmpdir, 'namoptions.001')))
E       AssertionError: assert False
E        +  where False = <function isfile at 0x102ee05e0>('/private/var/folders/mp/0nb6p8r96hg3157l6qwtf418000ctx/T/pytest-of-dpc/pytest-2/test_jinjaencoder1/namoptions.001')
E        +    where <function isfile at 0x102ee05e0> = <module 'posixpath' from '/Volumes/Samsung8TB/dpc/miniforge3/lib/python3.9/posixpath.py'>.isfile
E        +      where <module 'posixpath' from '/Volumes/Samsung8TB/dpc/miniforge3/lib/python3.9/posixpath.py'> = os.path
E        +    and   '/private/var/folders/mp/0nb6p8r96hg3157l6qwtf418000ctx/T/pytest-of-dpc/pytest-2/test_jinjaencoder1/namoptions.001' = <function join at 0x102ee0dc0>(local('/private/var/folders/mp/0nb6p8r96hg3157l6qwtf418000ctx/T/pytest-of-dpc/pytest-2/test_jinjaencoder1'), 'namoptions.001')
E        +      where <function join at 0x102ee0dc0> = <module 'posixpath' from '/Volumes/Samsung8TB/dpc/miniforge3/lib/python3.9/posixpath.py'>.join
E        +        where <module 'posixpath' from '/Volumes/Samsung8TB/dpc/miniforge3/lib/python3.9/posixpath.py'> = os.path

tests/test_jinja_encoder_new.py:147: AssertionError

Could this test be fixed?

**Comment by JonMcCullough** [comment]
Indicated problem file tests/test_jinja_encoder_new.py was not present in the tests folder (at least not in the dev or hackathon2024 branches). Not immediately found through a log search either. Existing test (tests/test_jinja_encoder.py) passed.
