### ISSUE TITLE
Refactoring Code for v0.1

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#39]
Looks like we now have a set of refactoring things which might be best handled prior to v0.1 (such as those arising from #32, #36 & #38). It is worth discussing what we want to do in order to meet goal of mid-month "release" and/or whether a delay is needed in that plan.

**Comment by dww100** [comment]
We should make small, contained issues and add them to the project so we can monitor progress.

**Comment by raar1** [comment]
(I'm happy to handle #32/#38, if you handle #36)
