### ISSUE TITLE
Local running is horrible - need a better way (or remove entirely)

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#4]
The title more or less says it all - currently we just write `run_cmd` from the JSON to file (with some parsing to ensure that the path is absolute). This will die in many situations and doesn't even work for:
`python3 myscript.py input_file`.

**Comment by raar1** [comment]
Based on our discussion the other day, I'm opting more or less for the "remove entirely" option.

By this I mean that:

-  app_info no longer contains a "run_cmd" entry
-  generic_encoder no longer writes the run script (more generally, encoders should not be handling this anyway)
-  For the purposes of local testing, I have of course retained an ExecuteLocal() approach, but the run command is specified explicitly in the python script. This makes it a lot more transparent, and makes it clear that EasyVVUQ is not intending to handle execution __at all__.

Additionally, I've formalized the concept of applying an action to a run directory, by making a BaseAction class (thus consistent with the approach of other parts of the lib). ExecuteLocal is now a class extending BaseAction. You can use it to execute any shell command you like, but most obvious use is to execute the simulations locally for testing.

My changes are all in the local_running_is_horrible_issue_4 branch.

Let me know what you think
