### ISSUE TITLE
Scalable method of run information storage required

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#47]
The `Campaign` as currently designed uses dictionaries and files. In particular the number of files may prove a pain for applications with millions of runs. 

Solving this will involve some refactoring and feature additions:

- [ ] Abstract the run related functions in `Campaign` (add run etc.)
- [ ] Change state saving to allow run data storage outside the JSON state file
- [ ] Implement a scalable backend - initially SQL via sqlalchemy

Later on we will also want to support HDF5 files (main reason for this is supporting the VECMA Fusion use case)

**Comment by dww100** [comment]
@orbitfold will work on the initial refactoring and sqlalchemy implementation

**Comment by raar1** [comment]
All three points have essentially been addressed, or are being addressed in other issues.
