### ISSUE TITLE
Stochastic collocation (sampling) method from CWI

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#48]
Wouter just presented a python class he wrote that does stochastic collocation. It essentially generates a list of runs (sets of params), and then the final analysis once they have run.

As presented, it appears to slot into EasyVVUQ almost instantly, so we should really look at incorporating it quickly if possible. I'll need to speak to him about it first (this afternoon), but he says the code is already uploaded to the AUC github repo.

**Comment by dww100** [comment]
@raar1 @wedeling Is this code or some development of it now incorporated? If so lets close this issue - if not lets make it part of the roadmap for M12 release.

**Comment by djgroen** [comment]
@dww100 I believe it's part of http://www.github.com/wedeling/FabUQCampaign. See the example there...

**Comment by dww100** [comment]
The example references code which I think we merged in the M9 release of EasyVVUQ but I want to be sure that no more code is needed.

**Comment by wedeling** [comment]
Hi, sorry for the late reply, I'm a bit of a noob with Github issues. Anyway, SC is implemented, but it only works with uniform distirbutions so far. Today I'll start working to integrate my code with chaospy so that we can de SC with all the standard distributions.

**Comment by dww100** [comment]
Thanks @wedeling - I don't think we are all figuring out the best way to manage projects in an academic environment. Let me know if you would rather we put questions to you exclusively on Slack or linked to issues there to get your attention/feedback.

**Comment by wedeling** [comment]
Thanks. I like Slack, but I'll also keep an eye out from now on here
