### ISSUE TITLE
Elements that act on campaigns, but don't have to

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#49]
We need to better formalize the dual application of collation and analysis elements to campaigns/not-campaigns. By this I mean that certain elements can only in principle apply to a campaign object (or the algorithm currently only works with that), whereas others (primarily analysis elements) can use a campaign object, a pandas dataframe, a csv file etc as input.

When a campaign is provided, then the element application can be logged with that campaign. Else, we could log it elsewhere (or not). But the point is that the code is getting messy with all these possibilities, and we need a more elegant way to abstract out the data source and logging thereof.

**Comment by djgroen** [comment]
Perhaps we need to improve the nomenclature, and subcategorize the elements according to their scope of applicability?

**Comment by raar1** [comment]
This type of discussion is now being handled in #63
