### ISSUE TITLE
Need to create a user config file for adding encoders

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#5]
Maybe using something like appdirs: https://pypi.org/project/appdirs/

**Comment by raar1** [comment]
I think this is now essentially resolved via the "default_app_encoders.json" file

**Comment by dww100** [comment]
I think we still need to deal with this - it's for users to add non-standard encoders

**Comment by raar1** [comment]
OK, I believe I've resolved this issue in my user_encoders branch.

The BaseEncoder and BaseDecoder classes now keep track of any subclasses. Any time a class extends one of these Base classes, that class is automatically registered as an encoder/decoder.

For example, I have added a test that uses a custom encoder and decoder with gauss. The encoder declaration looks like:
`class GaussEncoder(BaseEncoder, encoder_name = "gauss"):`
where `encoder_name` is the string it will be referred to by in state files etc. Decoders are treated likewise.

When you import easyvvuq, the default *coders are naturally found and registered. But if you have custom *coders (as with the gauss case above) then all you need to do is import them to your script (as you would with any module you wanted to use). Easyvvuq will automatically register them. There is therefore no real internal distinction between default and custom *coders.

This has greatly simplified a few areas of the library, and avoids the need for additional json config files, decorators etc.

**Comment by raar1** [comment]
(to be clear - these custom encoders and decoders are not in the library, they can be anywhere on the file system)

**Comment by dww100** [comment]
This looks great.

If you edit MANIFEST.in to remove the two JSON files then I think it is ready for pulling to dev.
