### ISSUE TITLE
Reminder to implement parameter physical range checking

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#51]
The JSON input file has contained "allowed" parameter ranges for some time, but EasyVVUQ doesn't do anything with that yet. The idea is to immediately catch situations in which (input or output) values fall outside physically acceptable ranges (as specified by the user).

**Comment by dww100** [comment]
Duplicated in #81 
That issue suggests doing this at the point of adding a run.

**Comment by dww100** [comment]
Here is something that might be useful here:
https://docs.python-cerberus.org/en/stable/

For the longer term goal of physical reasonableness we could use a units module like:
https://github.com/pandegroup/openmm/tree/f9106ddb6a0d72c960c73b23ed0e07cd7190a80f/wrappers/python/simtk/unit
https://pint.readthedocs.io/en/0.9/

**Comment by raar1** [comment]
I have begun work on this now, wrapping the params dict inside a ParamsSpecification class that carries out verification related duties

**Comment by dww100** [comment]
Are you using cerberus? I was looking again and it looks to me like we could get the min/max stuff basically for free if we converted the input params into a schema.

**Comment by raar1** [comment]
I am using cerberus. It's now working for all tests, although we have to use slightly different terminology e.g. float, string, integer, and "allowed" instead of "options" etc. I also had to subclass the cerberus validator to make it ignore the "fixture" type. In future you can do your own validation for that, or map it to an existing type (string?).

In any case, we now (finally) have this range checking, and much more, so I'm closing this issue.
