### ISSUE TITLE
Clean implementation of nodes/weights communication between sampling and analysis elements in PCE/Stoch.Coll.

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#56]
At present both PCE and Stoch. Coll. approaches don't have anywhere standard to store their nodes and weights info which is needed by the analysis step, and the current hack is to effectively monkey patch the campaign object with those vars during execution of the sampling element.

A possible fix is to add a dedicated __weights variable to every individual run dictionary. By definition this would be null, and not used, but would provide a storage space for the PCE/SC sampling elements when necessary.

Would this generally work? Do all such collocation-style methods have a single weight var for each job run for each node?

**Comment by wedeling** [comment]
In SC (and I'm pretty sure in PCE as well), each run has a d-dimensional weight array, where d is the number of uncertain parameters. The total weight array that I'm storing in the campaign object is of size Ns x d, where Ns is the number of code runs. So I guess your approach would work.

**Edit**: But now that I think about it, the approach I use above might be a bit of an overkill. The tensor grid is very regular I don't need to store the Ns x d array. Just the d one-dimensional weights would work as well. If I have those I can create the full tensor product when it's time to do the analysis. Aren't the 1d rules already available in the campaign object, under campaign.vars? I'll try to change a few things now in my SC_Analysis module, to see if this will work.

**Comment by wedeling** [comment]
OK this seems to work in my case, I've pushed the changes. All I'm ever using now is the `campaign.vars` dictionary, which was already there, I'm not storing any additional variables to the campaign object. The `campaign_vars` is a dict with the **1D** collocation points and weights, which I created in the `distributions.py` module, as before.

When I create a SCSampler object, I'm creating a tensor product of colloc points in that class in the __init__ subroutine:

`xi = [all_vars[param]['xi_1d'] for param in all_vars.keys()]`
`self.xi_d = np.array(list(product(*xi)))`

I'm doing the same thing in the SCAnalysis class, only for the weights as well, see `load_samples` subroutine.

The only thing now is that when I'll move to chaospy, I will have to rewrite 'distributions.py' to keep campaign.vars the same as it is now, but I don't think that'll be an issue.

**Comment by wedeling** [comment]
btw, you can test this in the `run_SC_campaign.py` module in the tests directory

**Comment by dww100** [comment]
I think the best approach here is to create a new branch and then a pull request with [WIP] in the title (for work in progress). Then we can work on this as a specific feature. The basic idea seems good to me.

**Comment by jlakhlili** [comment]
I guess, it will be ok also for the PCE method. Indeed the total nodes is an array of dimension n_param*n_runs and the total weights is an array of dimension n_runs.  Reduce the storage for each run will be good. So, I will try to have __weights and __nodes variable to every individual run dictionary  and test the impact on the analysis part.

**Comment by wedeling** [comment]
OK I've done that. Not sure if I did the pull request right though, some checks have failed

**Comment by jlakhlili** [comment]
OK Wouter, thanks. I will push and test...

**Comment by raar1** [comment]
I checked which tests are failing, and it's only the pep8 stuff. I'm wondering whether we could tone that down a little or make it a non-critical check. Once you're happy with your changes, I can run it through autopep8 or something anyway, if you like.

**Comment by dww100** [comment]
Docs on how to tone down the tests:
https://pypi.org/project/pytest-pep8/
https://pep8.readthedocs.io/en/latest/intro.html#error-codes

**Comment by wedeling** [comment]
I moved my SC code to chaospy on the issue_56 branch. The script in tests/SC_easyvvuq/run_SC_Campaign.py contains an example test case. I still do not store anything in the Campaign object, and now use chaospy to compute nodes and weights from campaign.vars  when needed. Before, campaign.vars just contained all 1D nodes and weights, now it contains 1D chaospy distributions. Before, the polynomial order was implicitly contained in the number of nodes in campaign.vars, but now I have to pass the polynomial order to the SC Analysis class.

**Comment by jlakhlili** [comment]
I removed the nodes/weights from Campaign. To stores informations about the PCE element.
            - Multivariate distribution
            - The orthogonal polynomials P
            - The quadrature informations: order, rule and sparsity
            - Number of samples

**Comment by jlakhlili** [comment]
In PCESampler, the nodes/weights are no longer attached  to the Campaign object. I compute them again in analysis. For information, I did a memory profiling for cp.generate_quadrature call to get 1.7 millions nodes and weights (the worst case that we will have), the result is OK. We need 122.4MB (cf. attached image). This routine will be called just twice during the UQ program. 
Otherwise, I still use  the Campaign object to stores the following informations:
- Multivariate distribution
- The orthogonal polynomials.
- The quadrature order and rule.
- The sparsity (boolean).
- Number of samples.

But they will cost nothing.![gen_quad_mem_pro](https://user-images.githubusercontent.com/16169832/55254345-e63e8480-5257-11e9-9586-70c1cf680710.png)

**Comment by raar1** [comment]
@jlakhlili OK that looks good. As per #63 I am planning to have the current element (sampling, analysis or otherwise) state stored as part of the campaign object. This is to allow restarts.

In light of this it would be best now maybe to try storing all this stuff within the sampling element. Each element will have a ```serialize()``` function (or something with a similar name) that will allow its state to be stored in the database. The question will then be if we can efficiently store the state of the PCESampler (I suppose that will just be the 5 things you list above) in a dict-style object that can be fed to the database.

**Comment by raar1** [comment]
Hopefully in the end this could look similar for @wedeling 's implementation of SC.
