### ISSUE TITLE
Extending Campaigns and using multiple Campaigns in a UQP

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#6]
I was originally thinking of two things:

1. Need to add more runs to enhance sampling (i.e. more replicas to get converged result)
2. Might want to use different applications in a UQP that use different encoders

Could also have a situation where I run `Campaign A` and then `Campaign B` to sample different parameters but I now want to combine in a single analysis.

This also gets me wondering about scanning the `runs` dictionary to check for certain parameters and return relevant runs.

**Comment by dww100** [comment]
Point 1 is probably solved by the new design. At least conceptually.
Still need a solution to Point 2 - @raar1 should we start a more focused issue?

**Comment by raar1** [comment]
The building blocks are now there for both these points. More specific issues can be added later to finish this off.
