### ISSUE TITLE
Collation/Analysis elements should not be forced to always write the pandas dataframe/log files to disk

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#60]
This would cause issues for e.g. Jalal with his millions of runs.

**Comment by dww100** [comment]
Agree - very much fits in with the general scalability push. Should it be the default?

**Comment by raar1** [comment]
I think so - it's easy to add a flag to the init for an analysis element that does this.

**Comment by raar1** [comment]
OK, I've assigned this to myself

**Comment by raar1** [comment]
Could have a STORE flag for the whole campaign object (by default true), with optional STORE flag in the apply() method of elements, that will override this default.

**Comment by raar1** [comment]
This is being addressed in the refactoring
