### ISSUE TITLE
Transition all EasyVVUQ distributions to chaospy distributions

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#61]
We have agreed that having chaospy as a dependency is a very good idea, but now we need to adapt the existing elements so that they all use the chaospy distributions. At present a weird mixture of the old and "new" distros are used.

A potential problem here is that certain types that we want don't exist - e.g. histogram?

**Comment by djgroen** [comment]
@raar1 I found this:
https://chaospy.readthedocs.io/en/master/distributions/custom.html 

I think you can make a custom distribution to reflect a histogram?

**Comment by djgroen** [comment]
e.g., by subclassing the distribution.

**Comment by raar1** [comment]
Ah thanks, Derek! I will look into this.

**Comment by wedeling** [comment]
I have another dumb Github question. When I'm modifying my SC code to include chaospy, shall I do this on the dev branch or on the branch I created for issue 56? My feeling would be the latter since they both concern the weights and collocations points.

**Comment by raar1** [comment]
@wedeling I think it's completely fine to use the same branch as for #56

**Comment by wedeling** [comment]
Ok thanks, I'll do it in that one

**Comment by dww100** [comment]
Basic distributions converted, issue #69 raised for remaining more complex cases.
