### ISSUE TITLE
We should have sensible logging for all elements

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#66]
Eventually this should me standard Python logging - allowing warnings, info etc - and the more long term element execution order (now being moved into the campaign database). We can't know how workflows are going to be implemented so messages should be provided that give as much context as possible (albeit we cannot rely on having execution level information like node ID, etc).

Identified issues that need to be dealt with
-  Version of EasyVVUQ and the CampaignDB should be stored and a warning output if they are different
-  Elements should log start and finish where appropriate (key example here is for samplers which could conceivably need to be one shot).

**Comment by raar1** [comment]
We now use the python logging module and store easyvvuq version.
