### ISSUE TITLE
Campaign object should have __version__ and check against database

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#67]
The Campaign object should have something along the lines of ```get_version()``` (or a ```__version__``` member var). This could simply be the current version of EasyVVUQ. This version would also be stored in database to indicate what version created it. That way if a user attempts to continue a campaign using a newer version of EasyVVUQ it will (at the very least) issue a warning along the lines of "WARNING: Loaded database was created with an earlier version (0.1.1) of EasyVVUQ than the current version (0.1.4)" or words to that effect.

**Comment by orbitfold** [comment]
Should this be done now or after or as part of #72? I'm fine with either.

**Comment by dww100** [comment]
Maybe consider using Versioneer:
https://github.com/warner/python-versioneer

**Comment by dww100** [comment]
Is there a way of decoupling the database and campaign version?

**Comment by raar1** [comment]
I think this ties in with a deeper issue - if there are multiple campaigns stored in a single database, it will start getting really messy if campaigns from different easyvvuq versions were somehow stored in the same database, not least since easyvvuq versions determine what form they expect the database to have.

I think either it is a hard requirement that a database always contains campaigns from the same easyvvuq version (so no decoupling at all. Or we limit databases to having only one campaign at all, which is even easier.

**Comment by raar1** [comment]
@orbitfold It's been a while since I looked at this issue - did we ever get anywhere with it? Do you think there's a clean way to do this version check with the db as it stands?

**Comment by orbitfold** [comment]
> @orbitfold It's been a while since I looked at this issue - did we ever get anywhere with it? Do you think there's a clean way to do this version check with the db as it stands?

From the CampaignDB __init__ method query the database and see if it contains campaigns created with other versions of EasyVVUQ, if so throw a hissy fit?

**Comment by raar1** [comment]
That would be perfect.

**Comment by orbitfold** [comment]
Ok I'll take care of this.

**Comment by raar1** [comment]
OK thanks, seems to work for me too now.
