### ISSUE TITLE
Support for gradual collation

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#70]
As part of the scalability push, and also with the PJM work, we must now expect two things:

- Runs will be executed in batches (e.g. 100 at a time) and not all at once
- There may be so many runs that it is not viable to store all their output on disk at the same time

This obviously conflicts with the way aggregation is currently done, which expects all run output to be present, and decodes it all into a big dataframe in one go. We therefore need some sort of collation element that can be run on the campaign after each batch, that identifies/decodes/aggregates from those runs which are completed (and in the right order) and updates the output dataframe.

This shouldn't be too hard, but still leaves us with some issues to consider:

- We want to be able to "restart" the Campaign, which means the collation element must be able to store its present (partially aggregated) state.
- How often do we do this? When the dataframe is massive (>1e6 jobs) the I/O would seem excessive if we did this every batch of 100 jobs, for example. Maybe we'd want to store only every aggregation of 1000 jobs?
- If we store by appending to a file, do we want it in binary format to take up less space? (rather than a plain text tsv). Or do we want to store in the database itself using sqlalchemy? How expensive in terms of storage would that be?
- The whole point of this gradual approach is to relieve the file system from too many output files, so something would have to be deleting those run directories. Would that be this collation element itself? Or do we want the user to explicitly ask for that action in their script?
- Would some sort of pipeline setup be better, in which a collation element is set (just as an encoder, decoder, or sampling element would be) and automatically gets piped the decoded output as and when jobs terminate? I feel we need something like this for the PJM case to look elegant.

**Comment by raar1** [comment]
As an afterthought:

The deletion of output files could be carried out by the decoder itself. So, after every execution terminates, the decoder is automatically run. It then writes its distilled output to a small file (or to the database, somehow) and the rest of the output can be deleted. The collation element could then fetch this decoder output during aggregation steps.

Of course, this deletion would be optional, and off by default. But for expensive HPC workflows, we would want it to be automatically getting rid of run directory info once the decoder has acted successfully. Successfully means the decoder thinks the run ended normally - if it crashed or expected data is missing then the run dir could be left behind for inspection/debugging.

**Comment by wedeling** [comment]
I think this would be a useful feature. I have a fancy adaptive collocation method lying around, which I was thinking of proposing to include. Something like this would be great for that.

**Comment by raar1** [comment]
Based on current discussion with @dww100 
* Flag recording whether a run's results have been decoded and aggregated into the dataframe (or not) should probably be part of the state of the collation element
* Collation element is likely to be an element very close to, or with different implementations for, different middlewares
* Should Collation state also handle the target_dir that each run has (rather than storing it in the Runs table as at present)? I think, e.g., ```populate_runs_dir()``` should actually be a function of the collation element. Possibly the execution step too.

**Comment by raar1** [comment]
Gradual collation is now implemented in the abstract_db_issue_72 branch.

```populate_runs_dir()``` and ```apply_for_each_run_dir()``` both now only act on runs with status ```created``` (thus avoiding runs with status ```completed```). This means only newly added runs will be encoded/executed.

Just call ```my_campaign.collate()``` whenever you like, and it will decode and aggregate any new results into the existing dataframe. To see the aggregated results, use ```my_campaign.get_last_collation()```
