### ISSUE TITLE
Access instance dictionary  in _log_analysis

### ISSUE THREAD

**Issue by jlakhlili** [UCL-CCS/EasyVVUQ#71]
To save the application log after running element specific analysis, the `_log_analysis` routine, called by `apply` routine, uses the access instance dictionary by calling `__dict__ `.  This call restrict attribute's typing in `BaseAnalysisElement` subclasses. 
I have cases in PCEAnaylis where I want to use a dictionaries to store descriptive statistics as new attributes. But each item values should be list, tuple of another dictionary. I can't use `ndarray` for example, otherwise I get the following error:

> AttributeError:  'numpy.ndarray' object has no attribute `__dict__`

Can we handle this problem by some modifications before application log? I suggest also to use Pickle for exapmle, I think that the manipulation of `__dict__ ` is not recommended.

**Comment by dww100** [comment]
Should be fixed by refactor
