### ISSUE TITLE
Integration with QCG-PJ

### ISSUE THREAD

**Issue by bartoszbosak** [UCL-CCS/EasyVVUQ#73]
I've just created the **qcgpj_integration** branch with the new test **pce_pj** based on a test of **pce** application, that brings the proposition of integration of EasyVVUQ with QCG-PilotJob Manager. This proposition is external to the current code of EasyVVUQ - everything is contained inside the **pce_pj** directory.

Since I've developed it using PyCharm and vagrant VM on my personal computer it could be quite difficult to test the solution in a different environment, but for sure you can look at the code. The idea is to have a PJConfigurator object that can store the execution configuration in one process and can load this configuration in the other. Currently it allows to run the encoding and executing phases in parallel using PJ. It was more difficult to do the same for aggregation and therefore it is still realised serially. 

I think it would be nice to move some of the code stored in PJConfigurator into EasyVVUQ, but, as you can see, the integration may be in large extent realised externally. What do you think about this solution?

**Comment by bartoszbosak** [comment]
Just for your information: I've managed to adjust the test and now it is successfully running with Travis.

**Comment by raar1** [comment]
@dww100 and I will now adapt @bartoszbosak 's code to the new refactored EasyVVUQ

**Comment by dww100** [comment]
Integration development moved to: https://github.com/vecma-project/EasyVVUQ-QCGPJ
