### ISSUE TITLE
PCE test in abstract_db_issue_72 branch

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#77]
I have made a first draft. Needs to be reviewed (it now runs to completion).

Known issues/improvements needed:
1. Only produces first order Sobol indices
  -  Should we add at least 2nd order? Would use `cp.Sens_m2` I guess? What is the likely limit in the end?
  -  Can we get Total-effect index?
2. Result dictionary need to be formalised
3. I have no idea if the results are correct

**Comment by jlakhlili** [comment]
1. We can add the 2nd order and total order using  `cp.Sens_m2` and `cp.Sens_t`. I can do it also after the merge and test it.
2. What do you mean by result dictionary? the `self._statistical_moments`  etc.. ?

**Comment by dww100** [comment]
In terms of the results dictionary what I mean is that we need to have some standard output from the analysis - the obvious option is the dictionary with 'statistical_moments' etc. It will probably make more sense when we merge the refactoring and you look at the updated code.

**Comment by jlakhlili** [comment]
OK! Thanks.
