### ISSUE TITLE
Implement resurrection of elements

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#78]
At present many elements (samplers, encoders etc) are able to serialize their states, which can then be stored in the campaign database. This allows them (in principle) to be re-initialised in cases where the campaign is restarted. However, at present this functionality is not implemented, and the campaign object contains references to the "live" element objects in use by the current app (such as ```campaign._active_app_encoder```), which are not appropriately switched when an app is switched either.

Some questions:
* Do we continue to store the reference to the live object in the campaign object like this?
* Do we always obtain the live object from the campaign database? If so, we need some sort of flag to stop it deserailizing the element from disk when it already exists.

**Comment by dww100** [comment]
- [ ] Encoders
- [ ] Decoders
- [ ] Samplers

**Comment by raar1** [comment]
I've implemented resurrection of these 4 elements in the refactor branch
