### ISSUE TITLE
Campaign method```collate()``` doesn't work when ```store``` set to True

### ISSUE THREAD

**Issue by raar1** [UCL-CCS/EasyVVUQ#83]
Do we fix this (allow individual collate() calls to automatically write the resulting dataframe to disk) or do we put this functionality somewhere else?

**Comment by dww100** [comment]
Maybe delete for now and then fix as part of continuous collation changes.

**Comment by raar1** [comment]
I've deleted the broken store code. Storage of the collated results will be tackled as part of Issue #70
