### ISSUE TITLE
Change lookup heuristic for templates define in input.json files to look relative to that directory.

### ISSUE THREAD

**Issue by djgroen** [UCL-CCS/EasyVVUQ#86]
Hi both,

Currently, when loading an input.json into EasyVVUQ, it will do a lookup for the defined template files relative to the location where you run the main Python script. 

This works for one-shot scripts, but in the case of FabUQCampaign we have a script that will be more flexible, and we place the template files in the same directory where we place the input.json file for the application (so we have all the EasyVVUQ input files conveniently in one directory).

Would it be possible to modify the lookup so that this can be supported?

**Comment by dww100** [comment]
Done
