### ISSUE TITLE
EasyVVUQ in Windows

### ISSUE THREAD

**Issue by wedeling** [UCL-CCS/EasyVVUQ#87]
Daan and I tried to run some of the tests (Cannonball and SC test) in Windows (using EasyVVUQ version 0.2), and ran into some issues with the `ExecuteLocal` subroutine. Maybe these issues will be obsolete with the refactored version, but we decided to let you know anyway

1) The shebang `!#` does not work in Windows, so to make `uq.actions.ExecuteLocal("run_ADE.py ade_in.json")` work, we have to hard code `'python '` in front of the `self.run_cmd` variable in `execute_local.py`. Changing `uq.actions.ExecuteLocal("run_ADE.py ade_in.json")` to `uq.actions.ExecuteLocal("python run_ADE.py ade_in.json")` does not work, since it then adds the run directory of `run_ADE.py` in front of `python`.

2) In `execute_local.py`, the lines  `full_cmd = 'cd ' + dirname + '\n' + self.run_cmd + '\n'`
 and `result = os.system(full_cmd)` did not work in Windows. For some reason we had to use `os.chdir` to change the working directory instead of `os.system`.

We will not push our changes to `execute_local.py`.

**Comment by dww100** [comment]
I don't think we will implement running locally on Windows. So I have added an exception to `ExecuteLocal` which explains that it is not implemented.
