### ISSUE TITLE
Scipy 1.3.0 changed API and now it doesn't work with Chaospy

### ISSUE THREAD

**Issue by bartoszbosak** [UCL-CCS/EasyVVUQ#88]
I've realised that the default dependency of Chaospy for Scipy is now not working. Until Chaospy updates to the changes done in the recents Scipy the solution is to specify an exact version for scipy in requirements.txt:
scipy==1.2.1
This is already done in qcgpj_integration branch.

**Comment by dww100** [comment]
I'll propagate your change when we push the refactoring to the main branch (if still relevant).

I have submitted a pull request at chaospy to fix the underlying issue:
https://github.com/jonathf/chaospy/pull/141

**Comment by dww100** [comment]
Requirements updated - will review version dependency at next release.
