### ISSUE TITLE
Reimplement replication of runs as a separate sampler

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#90]
We have a sampler that copies runs, would it be better to implement a 'replicas' option in a given sampler so that it can be done in one call?

i.e. 
```
sampler1 = uq.sampling.RandomSampler(vary=vary)
.
.
.
sampler2 = uq.sampling.Replicate(replicates=1)
```
becomes
```
sampler1 = uq.sampling.RandomSampler(vary=vary, replicas=2)
```

**Comment by dww100** [comment]
Replica option now in `Campaign.draw_samples`.

Still need a separate sampler as the use case is different - additional sampling after an analysis step suggests it is necessary.

**Comment by dww100** [comment]
When we do this we should add a flag for random seed variables - which should be altered for each replicated run.

**Comment by raar1** [comment]
Will this flag be something in the params block defined for a given app? So we would have a ```"resample_on_copy": True``` sort of thing there?

**Comment by dww100** [comment]
I think the resample with copy is the right idea but it needs to be a list of fields (e.g. random seeds only).

**Comment by dww100** [comment]
Further discussion in CCS yielded the idea of flagging seeds in sampler (which already has the way to sample them) and copy element de-serializing sampler relevant to the ensemble being extended.
