### ISSUE TITLE
Status should be specified using an ENUM

### ISSUE THREAD

**Issue by dww100** [UCL-CCS/EasyVVUQ#91]
Currently a free text string - an issue is that there is no universal ENUM type implementation in SQL - but conversion should be fairly easy.

**Comment by raar1** [comment]
Mapping the enum to an int for storage should work fine, although this will make the easyvvuq version check more important (as changes in any given status->int could really mess up restarts)

**Comment by raar1** [comment]
I've implemented enum run statuses in the dev branch now
